# Generated by Django 2.2.9 on 2020-02-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('categoryID', models.CharField(max_length=250)),
                ('categoryName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='static/images')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierID', models.CharField(max_length=250)),
                ('companyName', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('contactName', models.CharField(max_length=255)),
                ('contactTitle', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('fax', models.CharField(max_length=255)),
                ('homePage', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'supppliers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=255, unique=True)),
                ('productName', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('quantityPerUnit', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('unitsOnOrder', models.CharField(choices=[('onorder', 'Onorder'), ('notonorder', 'None')], default='None', max_length=255)),
                ('reorderLevel', models.IntegerField()),
                ('discontinued', models.CharField(choices=[('discontinued', 'Discontinued'), ('continued', 'Continued')], default='Continued', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_manager', to=settings.AUTH_USER_MODEL)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Categories')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Suppliers')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('unitPrice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('placed', 'Placed')], default='Placed', max_length=9)),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Products')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
